version: '3.8'

services:
  frontend:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development

  backend:
    image: python:3.9-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: sh -c "pip install -r requirements.txt && python app.py"
    environment:
      - FLASK_ENV=development

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=adhd_2e
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  default:
    name: adhd_2e_network
